export const DUMMY_ADDRESS_INPUTS = [
  {
    type: "text",
    name: "cep",
    placeholder: "CEP",
    required: true,
    inputClassName: "col-span-1",
  },
  {
    type: "text",
    name: "rua",
    placeholder: "Rua",
    required: true,
    inputClassName: "col-span-3",
  },
  {
    type: "text",
    name: "numero",
    placeholder: "Número",
    required: true,
    inputClassName: "col-span-1",
  },
  {
    type: "text",
    name: "complemento",
    placeholder: "Complemento",
    required: true,
    inputClassName: "col-span-2",
  },
  {
    type: "text",
    name: "bairro",
    placeholder: "Bairro",
    required: true,
    inputClassName: "col-span-1",
  },
  {
    type: "text",
    name: "cidade",
    placeholder: "Cidade",
    required: true,
    inputClassName: "col-span-1",
  },
  {
    type: "text",
    name: "uf",
    placeholder: "UF",
    required: true,
    inputClassName: "col-span-1",
  },
];
